### PR TITLE
Kelly

### PR DESCRIPTION
**Pull request by kelly-shen**
added google authentication so that users can find contacts from google contacts.

a sizable number of migration files got deleted when I did migration in order to create a model for googleinfo. I'm not sure if this would cause any problem, the website works fine on my local machine.

### CODE REVIEW

**Comment by karger** [comment]
I don't think make migrations is supposed to delete Any unless you tell it to so that should be investigated.

**Comment by kelly-shen** [comment]
yes, I did delete them when I committed... I'll revert to two commits back,
make the same changes to add google oauth and only commit those, and then
pull.

**Comment by karger** [comment]
I suggest figuring out what is going on before doing a whole series of
commits that might have to be reverted, muddying the commit log

**Comment by kelly-shen** [comment]
I agree! Actually I think I probably did migration wrong because I only
have migrations 0001-0003:

accounts/migrations/0001_initial.pynew file:
accounts/migrations/0002_auto__del_googleinfo.py
accounts/migrations/0003_auto__add_googleinfo.py

while the master branch has 0001-0007 of all the previous changes. I'll
revert back and migrate again.

**Comment by kelly-shen** [comment]
I am making a new pull request.

**Pull request closed without merging**
