### PR TITLE
Backend for tagging and highlighting app

### PR DESCRIPTION
**Pull request by jesszwang**
Backend functionality for tagging and highlighting app. Commits have been completely restructured and cleaned up. @amyxzhang, this branches cleanly off of https://github.com/haystack/eyebrowse-server/commit/7083fa2bbff29a2fa817c031dce04e8e2377a225 but not master, would need to roll back master to before my first pull request. 

See https://github.com/haystack/eyebrowse-server/compare/7083fa2bbff29a2fa817c031dce04e8e2377a225...jesszwang:hl for clean comparison.

### CODE REVIEW

**Comment by jesszwang** [comment]
@amyxzhang, if you could take a look again - made the fix to Tag model we discussed yesterday

**Comment by amyxzhang** [comment]
I think populate_base_tags should not be inside __init__.py because it only needs to run once, not every time we start the server. 

The right way to run a one-time script to load something into the database is to add it as a script in /scripts or to make it a management command in /common/management/commands. Probably the former unless it's something that's going to be run periodically.

BTW I've gone ahead and reverted the prior pull request.

**Comment by jesszwang** [comment]
@amyxzhang, made the changes we discussed today other than dynamic regeneration of trie blob - where do you suggest storing the .dic file data?

**Comment by amyxzhang** [comment]
The .dic file is just a list of words for each tag so there could just be a table where each of the words are stored and associated with the tag. Feel free to put that in a different pull request.

**Comment by amyxzhang** [comment]
In another pull request we'll also have to do the data migration for EyeHistory, etc. to Page, etc.

**Comment by amyxzhang** [comment]
Make sure if you do future data model changes to work off of the master branch (after this pull request) so there's no need to do more reverts and backwards data migrations.

**Pull request merged**
